# When the phone is picked up, this audio plays after a certain delay, followed by a beep.
prompt_start_delay: 1
starting_audio_prompt_dir: prompts/beauty
prompt_closing_sound: prompts/beep.wav

# Max length for a recording.
recording_max_duration: 60

# ASR model options: `vosk`.
speech_to_text_model: vosk

# Response model options: `echo`, `random_markov`, `tiny_llama`, `deepseek`.
response_model: deepseek

# System prompts are only applicable for LLM models (`tiny_llama`, `deepseek`).
system_prompt: "Generate a simple 3-7-3 haiku based off the following text"

# API endpoint if using tiny_llama.
tiny_llama_api_url: "http://100.116.247.74:5000/generate"

# TTS model options: `command_line`, `google_tts`.
text_to_speech_model: google_tts
