# Recording parameters (VAD).
vad_api_url: "http://localhost:8010/record"
min_recording_duration: 2
max_recording_duration: 20 # 10
silence_duration_to_stop: 2 # 1

# Speech to text parameters (ASR).
asr_api_url: "http://localhost:8011/asr"
asr_model: vosk # Options: vosk.

# Response Parameters.
# response_api_url: "http://localhost:8012/response/stream"
response_api_url: "http://localhost:8012/response"
response_model: deepseek # Options: echo, random_markov, tiny_llama, deepseek, jeff.
system_prompt: "Give a short reply. Reply in no more than 30 words."
# system_prompt: "I am Jeff Bezos, a very rich man. I hate poor people. I love capitalism. Reply with no more than 15 words."

# Text to Speech parameters (TTS).
tts_api_url: http://localhost:8013/tts
text_to_speech_model: google_tts # Options: command_line, google_tts, pytts
tts_language: en
tts_file_output_path: "__output.wav"
# jeff_tts_model_url: http://100.116.247.74:5000/tts

# API endpoint for the printer server.
printer_server_url: http://100.114.191.58:5000/print
