# When the phone is picked up, this audio plays after a certain delay, followed by a beep.
prompt_start_delay: 1
starting_audio_prompt: prompts/cameron_says_hello.wav
prompt_closing_sound: promots/beep.wav

# Max length for a recording.
recording_max_duration: 60

# ASR model options: `vosk`.
speech_to_text_model: vosk

# Response model options: `echo`, `random_markov`.
response_model: echo

# TTS model options: `command_line`, `google_tts`.
text_to_speech_model: google_tts
